kind: pipeline
type: docker
name: deploy_puentecubanobot

trigger:
  branch:
    - master

volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock

steps:
- name: build
  image: docker:24.0
  commands:
    - docker build -t puentecubanobot .
  volumes:
    - name: docker_sock
      path: /var/run/docker.sock

- name: deploy
  image: docker:24.0
  environment:
   TELEGRAM_BOT_TOKEN:
     from_secret: TELEGRAM_BOT_TOKEN
   API_BASE_URL:
     from_secret: API_BASE_URL
  commands:
    - mkdir /puentecubanobot && mv * /puentecubanobot/ && cd /puentecubanobot
    - |
      cat > .env << EOF
      TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      API_BASE_URL=${API_BASE_URL}
      EOF
    - docker compose down || true
    - docker compose up -d --build --force-recreate
  volumes:
    - name: docker_sock
      path: /var/run/docker.sock
  depends_on:
    - build
